#!/usr/bin/zsh

usage() {
	echo "Usage: $0 -c (class name) -f (file to rename)"
}

CONFIG_FILE="modules.conf"

class=""
file=""

while getopts "c:f:h" option; do
	case "$option" in
		c)
			class=$OPTARG
			;;
		f)
			file=$OPTARG
			;;
		h)
			usage
			;;
		*)
			usage
			;;
	esac
done

if [[ -z "$class" || -z "$file" ]]; then
	echo "Missing options!"
	usage
	exit 1
fi

grep $class $CONFIG_FILE -n > /dev/null

if [ $? -eq 1 ]; then
	echo "$class does not exist"
	exit 1
fi

class_name="INFO"
class_name+=$(grep $class $CONFIG_FILE -n | cut -f1 -d:)

base_name=$(perl -pe "s/^.*(?=(_[psPS]_))//g;" -pe "s/(_f)?(_v[0-9{2}][a-z]?)?//g" <<< "$file")

file_name="$class_name"
file_name+="_"
file_name+="$class"
file_name+="$base_name"

directory_name=$(perl -pe "s/^.*(?=([0-9]{4}))//g;" -pe "s/\..*$//g" <<< "$base_name")

mkdir "$directory_name"
mv $file $file_name

mv $file_name $directory_name

exit 0
